//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.ObjectModel;

    public partial class Libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libros()
        {
            this.Autores = new ObservableCollection<Autores>();
        }

        public int IdLibro { get; set; }
        public string Titulo { get; set; }
        public System.DateTime FechaDeRecepcion { get; set; }
        public int Calificacion_EstructuraGeneral { get; set; }
        public int Calificacion_Introduccion { get; set; }
        public int Calificacion_CongruenciaMetodologica { get; set; }
        public int Calificacion_Resultados { get; set; }
        public int Calificacion_LiteraturaCitada { get; set; }
        public byte Aprobado { get; set; }
        public System.DateTime FechaDeLiberacion { get; set; }
        public int IdEstado { set; get; }

        public int CalificacionTotal
        {
            get
            {
                int calificacionTotal =
                this.Calificacion_EstructuraGeneral
                + this.Calificacion_Introduccion
                + this.Calificacion_CongruenciaMetodologica
                + this.Calificacion_Resultados
                + this.Calificacion_LiteraturaCitada;
                return calificacionTotal;
            }

        }

        public string NombreEstado { get { return this.Estados.NombreEstado; } }

        public string NombresAutores
        {
            get
            {
                string nombresDeAutores = "";
                foreach (Autores autor in this.Autores)
                {
                    nombresDeAutores += autor.Apellido + ", " + autor.Iniciales + "; ";
                }
                return nombresDeAutores;
            }
        }

        public void Aprobar()
        {
            int calificacionTotal =
                this.Calificacion_LiteraturaCitada
                + this.Calificacion_CongruenciaMetodologica
                + this.Calificacion_Resultados
                + this.Calificacion_EstructuraGeneral
                + this.Calificacion_Introduccion;
            if (calificacionTotal > 69)
            {
                this.Aprobado = 1;
            }
            else
            {
                this.Aprobado = 0;
            }
        }

        public void SetEstadoDeEvaluacion(bool fueAceptado)
        {
            Estados newEstado = new Estados();
            if (fueAceptado)
            {
                newEstado.NombreEstado = EstadosDeLibro.Evaluado.ToString();
                newEstado.IdEstado = (int)EstadosDeLibro.Evaluado;

            }
            else
            {
                newEstado.NombreEstado = EstadosDeLibro.Rechazado.ToString();
                newEstado.IdEstado = (int)EstadosDeLibro.Rechazado;
            }
            this.Estados = newEstado;
            this.IdEstado = newEstado.IdEstado;
        }

        public Estados Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ObservableCollection<Autores> Autores { get; set; }
    }
}
